# Generated by Django 4.1.1 on 2022-09-13 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cartas3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('Url', models.URLField(blank=True)),
            ],
        ),
    ]
